services:
  # Frontend React App
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - oracle-db
    networks:
      - prisoner-network

  # Backend API Service
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      - PORT=4000
      - DB_HOST=oracle-db
      - DB_PORT=1521
      - DB_USER=system
      - DB_PASSWORD=ITC341ProjectPassword
      - DB_DATABASE=xepdb1
    volumes:
      - ./init-scripts:/app/init-scripts
    networks:
      - prisoner-network
    restart: on-failure

  # Oracle DB - using publicly available Oracle XE image
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    environment:
      - ORACLE_PASSWORD=ITC341ProjectPassword
      - ORACLE_DATABASE=XE
      # Ensure data persistence
      - ORACLE_CHARSET=AL32UTF8
      - ORACLE_EDITION=xe
      # For easier debugging
      - ORACLE_DISABLE_ASYNCH_IO=true
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-setup:/opt/oracle/scripts/setup
      - oracle-startup:/opt/oracle/scripts/startup
      - ./init-scripts:/container-entrypoint-initdb.d
    networks:
      - prisoner-network
    healthcheck:
      # Improved healthcheck to verify database is actually accessible
      test: [ "CMD", "sqlplus", "-L", "system/ITC341ProjectPassword@//localhost:1521/xepdb1", "AS", "SYSDBA", "<<< 'SELECT 1 FROM DUAL;'" ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    # Improve container shutdown to prevent data corruption
    stop_grace_period: 30s

networks:
  prisoner-network:
    driver: bridge

volumes:
  oracle-data:
    name: oracle-prison-data
  oracle-setup:
    name: oracle-prison-setup
  oracle-startup:
    name: oracle-prison-startup 